apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  selector:
    app: web
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: adamwu/netcoreweb:v1.1
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:80;https://+:443"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          value: "password01"
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: /app/cert.pfx