apiVersion: v1
kind: Service
metadata:
  name: api-svc
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  api-mapping
      prefix: /api/
      service: api-svc
spec:
  selector:
    app: api-b
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80