apiVersion: v1
kind: Service
metadata:
  name: api-b-svc
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  api-b-mapping
      prefix: /api-b/
      service: api-b-svc
spec:
  selector:
    app: api-b
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-b-deploy
  labels:
    app: api-b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-b
  template:
    metadata:
      labels:
        app: api-b
    spec:
      containers:
      - name: api-b
        image: adamwu/netcoreapi:v1.8
        ports:
        - containerPort: 80